spring.application.name=backend
spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}
#spring.security.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zenalert.app@gmail.com
spring.mail.password=arrdsninylaskthj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
